// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Playlist.Data;

namespace Playlist.Migrations
{
    [DbContext(typeof(PlaylistContext))]
    partial class PlaylistContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.13")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Playlist.Data.Models.Kategorija", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Naziv")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Kategorija");

                    b.HasData(
                        new
                        {
                            Id = 2,
                            Naziv = "Pop"
                        },
                        new
                        {
                            Id = 3,
                            Naziv = "Rock"
                        },
                        new
                        {
                            Id = 4,
                            Naziv = "Narodna"
                        },
                        new
                        {
                            Id = 5,
                            Naziv = "Jazz"
                        },
                        new
                        {
                            Id = 6,
                            Naziv = "Heavy metal"
                        },
                        new
                        {
                            Id = 7,
                            Naziv = "Klasična"
                        },
                        new
                        {
                            Id = 8,
                            Naziv = "Turbofolk"
                        },
                        new
                        {
                            Id = 9,
                            Naziv = "Rep"
                        },
                        new
                        {
                            Id = 10,
                            Naziv = "Reggae"
                        });
                });

            modelBuilder.Entity("Playlist.Data.Models.Pjesma", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("DatumEditovanja")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DatumUnosa")
                        .HasColumnType("datetime2");

                    b.Property<bool>("JeLiFavorit")
                        .HasColumnType("bit");

                    b.Property<int>("KategorijaId")
                        .HasColumnType("int");

                    b.Property<string>("Naziv")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NazivIzvodjaca")
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte?>("Ocjena")
                        .HasColumnType("tinyint");

                    b.Property<string>("Url")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("KategorijaId");

                    b.ToTable("Pjesma");
                });

            modelBuilder.Entity("Playlist.Data.Models.Pjesma", b =>
                {
                    b.HasOne("Playlist.Data.Models.Kategorija", "Kategorija")
                        .WithMany("Pjesme")
                        .HasForeignKey("KategorijaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Kategorija");
                });

            modelBuilder.Entity("Playlist.Data.Models.Kategorija", b =>
                {
                    b.Navigation("Pjesme");
                });
#pragma warning restore 612, 618
        }
    }
}
